Host-specific folder and Makefile for all

diff --git a/test-mon86-stub b/test-mon86-stub
--- a/test-mon86-stub
+++ b/test-mon86-stub
@@ -2,6 +2,11 @@
 
 # Test MON86 stub on host
 
-./mon86-stub <test-mon86-in.txt >test-mon86-out.txt
+host/mon86-stub <test-mon86-in.txt >test-mon86-out.txt
 
 diff test-mon86-ref.txt test-mon86-out.txt
+if (( $? > 0 )); then
+	echo "FAILED"
+	else
+	echo "PASSED"
+	fi
